meta_product_name: "ReelMates"
meta_title: "ReelMates - Discover Movies Everyone Will Love"
meta_description: "The fun, hassle-free way for couples and friends to discover movies everyone will love from the comfort of their couch."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
